[general]
# Default tool
initial-tool = "rectangle"
# Smaller annotations
annotation-size-factor = 1
output-filename = "/home/dylan/Images/Screenshots/%Y-%m-%d_%H:%M:%S.png"

[color-palette]
# Keep a minimal palette with red
palette = ["#ff0000"]
custom = ["#ff0000"]
