# Yazi Configuration
# Main settings for yazi file manager

[mgr]
show_hidden = true
sort_by = "mtime"
sort_dir_first = false
sort_reverse = true
linemode = "size_and_mtime"

[preview]
max_width = 1920
max_height = 1080

[flavor]
use = "noctalia"

[log]
enabled = true

[[previewers.prepend]]
mime = "application/zip"
run = "ouch"

[[previewers.prepend]]
mime = "application/tar"
run = "ouch"

[[previewers.prepend]]
mime = "application/bzip2"
run = "ouch"

[[previewers.prepend]]
mime = "application/7z-compressed"
run = "ouch"

[[previewers.prepend]]
mime = "application/rar"
run = "ouch"

[[previewers.prepend]]
mime = "application/xz"
run = "ouch"
